version: 2.1
jobs:
  php80:
    docker:
      - image: php:8.0-cli
    steps:
      - checkout
      - run: apt-get update && apt-get install -y git
      - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - run: composer update -n
      - run: phpdbg -qrr vendor/bin/phpunit
      - run: vendor/bin/phpstan analyse
      - run: vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation
  php80-minimal:
    docker:
      - image: php:8.0-cli
    steps:
      - checkout
      - run: apt-get update && apt-get install -y git
      - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - run: composer update -n --prefer-lowest
      - run: phpdbg -qrr vendor/bin/phpunit
      - run: vendor/bin/phpstan analyse
      - run: vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation
  php74:
    docker:
      - image: php:7.4-cli
    steps:
      - checkout
      - run: apt-get update && apt-get install -y git
      - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - run: composer update -n
      - run: phpdbg -qrr vendor/bin/phpunit
      - run: vendor/bin/phpstan analyse
      - run: vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation
  php74-minimal:
    docker:
      - image: php:7.4-cli
    steps:
      - checkout
      - run: apt-get update && apt-get install -y git
      - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - run: composer update -n --prefer-lowest
      - run: phpdbg -qrr vendor/bin/phpunit
      - run: vendor/bin/phpstan analyse
      - run: vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation
  php73:
    docker:
      - image: php:7.3-cli
    steps:
      - checkout
      - run: apt-get update && apt-get install -y git
      - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - run: composer update -n
      - run: phpdbg -qrr vendor/bin/phpunit
      - run: vendor/bin/phpstan analyse
      - run: vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation
  php73-minimal:
    docker:
      - image: php:7.3-cli
    steps:
      - checkout
      - run: apt-get update && apt-get install -y git
      - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - run: composer update -n --prefer-lowest
      - run: phpdbg -qrr vendor/bin/phpunit
      - run: vendor/bin/phpstan analyse
      - run: vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation
  php72:
    docker:
      - image: php:7.2-cli
    steps:
      - checkout
      - run: apt-get update && apt-get install -y git
      - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - run: composer update -n
      - run: phpdbg -qrr vendor/bin/phpunit
      - run: vendor/bin/phpstan analyse
      - run: vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation
  php72-minimal:
    docker:
      - image: php:7.2-cli
    steps:
      - checkout
      - run: apt-get update && apt-get install -y git
      - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - run: composer update -n --prefer-lowest
      - run: phpdbg -qrr vendor/bin/phpunit
      - run: vendor/bin/phpstan analyse
      - run: vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation
  php71:
    docker:
      - image: php:7.1-cli
    steps:
      - checkout
      - run: apt-get update && apt-get install -y git
      - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - run: composer update -n
      - run: phpdbg -qrr vendor/bin/phpunit
      - run: vendor/bin/phpstan analyse
      - run: vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation
  php71-minimal:
    docker:
      - image: php:7.1-cli
    steps:
      - checkout
      - run: apt-get update && apt-get install -y git
      - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - run: composer update -n --prefer-lowest
      - run: phpdbg -qrr vendor/bin/phpunit
      - run: vendor/bin/phpstan analyse
      - run: vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation
workflows:
  version: 2
  build_and_test:
    jobs:
      - php80
      - php80-minimal
      - php74
      - php74-minimal
      - php73
      - php73-minimal
      - php72
      - php72-minimal
      - php71
      - php71-minimal
